// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7cADEz7YJ3YTETgAWt9FpdxqXrqr2Xp8',
    appId: '1:776890628143:android:3a335e08a6f15d1901eeda',
    messagingSenderId: '776890628143',
    projectId: 'aikido-kalamata-app',
    storageBucket: 'aikido-kalamata-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzVV0M_LevNthqmKODrj3W9jg_XA2KqZU',
    appId: '1:776890628143:ios:0a8ea9a5e45a7e3b01eeda',
    messagingSenderId: '776890628143',
    projectId: 'aikido-kalamata-app',
    storageBucket: 'aikido-kalamata-app.firebasestorage.app',
    androidClientId: '776890628143-j1elefgckk69ra9t6e0i9mvrleicg2ap.apps.googleusercontent.com',
    iosClientId: '776890628143-6h3q297nklgl19iiojl51dl28ntcm9gj.apps.googleusercontent.com',
    iosBundleId: 'com.example.aikidoKalamataApp',
  );

}